name: VoidCashKill
main: AdminBuilder1\voidcashkill\voidcashkill
description: Void kills, coded by AdminBuilder1 for LanternMC
website: https://github.com/surveybuilderteams/VoidCashKill
api: [3.22.0, 3.22.1]
version: 1.0.1

permissions:
    vck.cmd:
        description: "Allows users to get coins"
        default: true
